// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission_12.Models;

namespace Mission_12.Migrations
{
    [DbContext(typeof(AppointmentsContext))]
    [Migration("20220321205942_Appointments")]
    partial class Appointments
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23");

            modelBuilder.Entity("Mission_12.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TimeSlotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppointmentId");

                    b.HasIndex("TimeSlotId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Mission_12.Models.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Booked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Booked = false,
                            Date = "03-22-2021",
                            Time = "08:00"
                        },
                        new
                        {
                            Id = 2,
                            Booked = false,
                            Date = "03-22-2021",
                            Time = "09:00"
                        },
                        new
                        {
                            Id = 3,
                            Booked = false,
                            Date = "03-22-2021",
                            Time = "10:00"
                        },
                        new
                        {
                            Id = 4,
                            Booked = false,
                            Date = "03-22-2021",
                            Time = "11:00"
                        },
                        new
                        {
                            Id = 5,
                            Booked = false,
                            Date = "03-22-2021",
                            Time = "12:00"
                        },
                        new
                        {
                            Id = 6,
                            Booked = false,
                            Date = "03-22-2021",
                            Time = "13:00"
                        },
                        new
                        {
                            Id = 7,
                            Booked = false,
                            Date = "03-22-2021",
                            Time = "14:00"
                        },
                        new
                        {
                            Id = 8,
                            Booked = false,
                            Date = "03-22-2021",
                            Time = "15:00"
                        },
                        new
                        {
                            Id = 22,
                            Booked = false,
                            Date = "03-22-2021",
                            Time = "16:00"
                        },
                        new
                        {
                            Id = 23,
                            Booked = false,
                            Date = "03-22-2021",
                            Time = "17:00"
                        },
                        new
                        {
                            Id = 24,
                            Booked = false,
                            Date = "03-22-2021",
                            Time = "18:00"
                        },
                        new
                        {
                            Id = 25,
                            Booked = false,
                            Date = "03-22-2021",
                            Time = "19:00"
                        },
                        new
                        {
                            Id = 26,
                            Booked = false,
                            Date = "03-22-2021",
                            Time = "20:00"
                        },
                        new
                        {
                            Id = 9,
                            Booked = false,
                            Date = "03-23-2021",
                            Time = "08:00"
                        },
                        new
                        {
                            Id = 10,
                            Booked = false,
                            Date = "03-23-2021",
                            Time = "09:00"
                        },
                        new
                        {
                            Id = 11,
                            Booked = false,
                            Date = "03-23-2021",
                            Time = "10:00"
                        },
                        new
                        {
                            Id = 12,
                            Booked = false,
                            Date = "03-23-2021",
                            Time = "11:00"
                        },
                        new
                        {
                            Id = 13,
                            Booked = false,
                            Date = "03-23-2021",
                            Time = "12:00"
                        },
                        new
                        {
                            Id = 14,
                            Booked = false,
                            Date = "03-23-2021",
                            Time = "13:00"
                        },
                        new
                        {
                            Id = 15,
                            Booked = false,
                            Date = "03-23-2021",
                            Time = "14:00"
                        },
                        new
                        {
                            Id = 16,
                            Booked = false,
                            Date = "03-23-2021",
                            Time = "15:00"
                        },
                        new
                        {
                            Id = 17,
                            Booked = false,
                            Date = "03-23-2021",
                            Time = "16:00"
                        },
                        new
                        {
                            Id = 18,
                            Booked = false,
                            Date = "03-23-2021",
                            Time = "17:00"
                        },
                        new
                        {
                            Id = 19,
                            Booked = false,
                            Date = "03-23-2021",
                            Time = "18:00"
                        },
                        new
                        {
                            Id = 20,
                            Booked = false,
                            Date = "03-23-2021",
                            Time = "19:00"
                        },
                        new
                        {
                            Id = 21,
                            Booked = false,
                            Date = "03-23-2021",
                            Time = "20:00"
                        });
                });

            modelBuilder.Entity("Mission_12.Models.Appointment", b =>
                {
                    b.HasOne("Mission_12.Models.TimeSlot", "TimeSlot")
                        .WithMany()
                        .HasForeignKey("TimeSlotId");
                });
#pragma warning restore 612, 618
        }
    }
}
