// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission_12.Models;

namespace Mission_12.Migrations
{
    [DbContext(typeof(AppointmentsContext))]
    partial class AppointmentsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23");

            modelBuilder.Entity("Mission_12.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppointmentId");

                    b.HasIndex("TimeSlotId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Mission_12.Models.TimeSlot", b =>
                {
                    b.Property<int>("TimeSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Booked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TimeSlotId");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            TimeSlotId = 1,
                            Booked = false,
                            Date = "2022-03-22",
                            Time = "08:00"
                        },
                        new
                        {
                            TimeSlotId = 2,
                            Booked = false,
                            Date = "2022-03-22",
                            Time = "09:00"
                        },
                        new
                        {
                            TimeSlotId = 3,
                            Booked = false,
                            Date = "2022-03-22",
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 4,
                            Booked = false,
                            Date = "2022-03-22",
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 5,
                            Booked = false,
                            Date = "2022-03-22",
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 6,
                            Booked = false,
                            Date = "2022-03-22",
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 7,
                            Booked = false,
                            Date = "2022-03-22",
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 8,
                            Booked = false,
                            Date = "2022-03-22",
                            Time = "15:00"
                        },
                        new
                        {
                            TimeSlotId = 22,
                            Booked = false,
                            Date = "2022-03-22",
                            Time = "16:00"
                        },
                        new
                        {
                            TimeSlotId = 23,
                            Booked = false,
                            Date = "2022-03-22",
                            Time = "17:00"
                        },
                        new
                        {
                            TimeSlotId = 24,
                            Booked = false,
                            Date = "2022-03-22",
                            Time = "18:00"
                        },
                        new
                        {
                            TimeSlotId = 25,
                            Booked = false,
                            Date = "2022-03-22",
                            Time = "19:00"
                        },
                        new
                        {
                            TimeSlotId = 26,
                            Booked = false,
                            Date = "2022-03-22",
                            Time = "20:00"
                        },
                        new
                        {
                            TimeSlotId = 9,
                            Booked = false,
                            Date = "2022-03-23",
                            Time = "08:00"
                        },
                        new
                        {
                            TimeSlotId = 10,
                            Booked = false,
                            Date = "2022-03-23",
                            Time = "09:00"
                        },
                        new
                        {
                            TimeSlotId = 11,
                            Booked = false,
                            Date = "2022-03-23",
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 12,
                            Booked = false,
                            Date = "2022-03-23",
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 13,
                            Booked = false,
                            Date = "2022-03-23",
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 14,
                            Booked = false,
                            Date = "2022-03-23",
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 15,
                            Booked = false,
                            Date = "2022-03-23",
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 16,
                            Booked = false,
                            Date = "2022-03-23",
                            Time = "15:00"
                        },
                        new
                        {
                            TimeSlotId = 17,
                            Booked = false,
                            Date = "2022-03-23",
                            Time = "16:00"
                        },
                        new
                        {
                            TimeSlotId = 18,
                            Booked = false,
                            Date = "2022-03-23",
                            Time = "17:00"
                        },
                        new
                        {
                            TimeSlotId = 19,
                            Booked = false,
                            Date = "2022-03-23",
                            Time = "18:00"
                        },
                        new
                        {
                            TimeSlotId = 20,
                            Booked = false,
                            Date = "2022-03-23",
                            Time = "19:00"
                        },
                        new
                        {
                            TimeSlotId = 21,
                            Booked = false,
                            Date = "2022-03-23",
                            Time = "20:00"
                        },
                        new
                        {
                            TimeSlotId = 27,
                            Booked = false,
                            Date = "2022-03-24",
                            Time = "08:00"
                        },
                        new
                        {
                            TimeSlotId = 28,
                            Booked = false,
                            Date = "2022-03-24",
                            Time = "09:00"
                        },
                        new
                        {
                            TimeSlotId = 29,
                            Booked = false,
                            Date = "2022-03-24",
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 30,
                            Booked = false,
                            Date = "2022-03-24",
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 31,
                            Booked = false,
                            Date = "2022-03-24",
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 32,
                            Booked = false,
                            Date = "2022-03-24",
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 33,
                            Booked = false,
                            Date = "2022-03-24",
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 34,
                            Booked = false,
                            Date = "2022-03-24",
                            Time = "15:00"
                        },
                        new
                        {
                            TimeSlotId = 35,
                            Booked = false,
                            Date = "2022-03-24",
                            Time = "16:00"
                        },
                        new
                        {
                            TimeSlotId = 36,
                            Booked = false,
                            Date = "2022-03-24",
                            Time = "17:00"
                        },
                        new
                        {
                            TimeSlotId = 37,
                            Booked = false,
                            Date = "2022-03-24",
                            Time = "18:00"
                        },
                        new
                        {
                            TimeSlotId = 38,
                            Booked = false,
                            Date = "2022-03-24",
                            Time = "19:00"
                        },
                        new
                        {
                            TimeSlotId = 39,
                            Booked = false,
                            Date = "2022-03-24",
                            Time = "20:00"
                        },
                        new
                        {
                            TimeSlotId = 40,
                            Booked = false,
                            Date = "2022-03-25",
                            Time = "08:00"
                        },
                        new
                        {
                            TimeSlotId = 41,
                            Booked = false,
                            Date = "2022-03-25",
                            Time = "09:00"
                        },
                        new
                        {
                            TimeSlotId = 42,
                            Booked = false,
                            Date = "2022-03-25",
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 43,
                            Booked = false,
                            Date = "2022-03-25",
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 44,
                            Booked = false,
                            Date = "2022-03-25",
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 45,
                            Booked = false,
                            Date = "2022-03-25",
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 46,
                            Booked = false,
                            Date = "2022-03-25",
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 47,
                            Booked = false,
                            Date = "2022-03-25",
                            Time = "15:00"
                        },
                        new
                        {
                            TimeSlotId = 48,
                            Booked = false,
                            Date = "2022-03-25",
                            Time = "16:00"
                        },
                        new
                        {
                            TimeSlotId = 49,
                            Booked = false,
                            Date = "2022-03-25",
                            Time = "17:00"
                        },
                        new
                        {
                            TimeSlotId = 50,
                            Booked = false,
                            Date = "2022-03-25",
                            Time = "18:00"
                        },
                        new
                        {
                            TimeSlotId = 51,
                            Booked = false,
                            Date = "2022-03-25",
                            Time = "19:00"
                        },
                        new
                        {
                            TimeSlotId = 52,
                            Booked = false,
                            Date = "2022-03-25",
                            Time = "20:00"
                        },
                        new
                        {
                            TimeSlotId = 53,
                            Booked = false,
                            Date = "2022-03-26",
                            Time = "08:00"
                        },
                        new
                        {
                            TimeSlotId = 54,
                            Booked = false,
                            Date = "2022-03-26",
                            Time = "09:00"
                        },
                        new
                        {
                            TimeSlotId = 55,
                            Booked = false,
                            Date = "2022-03-26",
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 56,
                            Booked = false,
                            Date = "2022-03-26",
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 57,
                            Booked = false,
                            Date = "2022-03-26",
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 58,
                            Booked = false,
                            Date = "2022-03-26",
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 59,
                            Booked = false,
                            Date = "2022-03-26",
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 60,
                            Booked = false,
                            Date = "2022-03-26",
                            Time = "15:00"
                        },
                        new
                        {
                            TimeSlotId = 61,
                            Booked = false,
                            Date = "2022-03-26",
                            Time = "16:00"
                        },
                        new
                        {
                            TimeSlotId = 62,
                            Booked = false,
                            Date = "2022-03-26",
                            Time = "17:00"
                        },
                        new
                        {
                            TimeSlotId = 63,
                            Booked = false,
                            Date = "2022-03-26",
                            Time = "18:00"
                        },
                        new
                        {
                            TimeSlotId = 64,
                            Booked = false,
                            Date = "2022-03-26",
                            Time = "19:00"
                        },
                        new
                        {
                            TimeSlotId = 65,
                            Booked = false,
                            Date = "2022-03-26",
                            Time = "20:00"
                        },
                        new
                        {
                            TimeSlotId = 66,
                            Booked = false,
                            Date = "2022-03-27",
                            Time = "08:00"
                        },
                        new
                        {
                            TimeSlotId = 67,
                            Booked = false,
                            Date = "2022-03-27",
                            Time = "09:00"
                        },
                        new
                        {
                            TimeSlotId = 68,
                            Booked = false,
                            Date = "2022-03-27",
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 69,
                            Booked = false,
                            Date = "2022-03-27",
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 70,
                            Booked = false,
                            Date = "2022-03-27",
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 71,
                            Booked = false,
                            Date = "2022-03-27",
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 72,
                            Booked = false,
                            Date = "2022-03-27",
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 73,
                            Booked = false,
                            Date = "2022-03-27",
                            Time = "15:00"
                        },
                        new
                        {
                            TimeSlotId = 74,
                            Booked = false,
                            Date = "2022-03-27",
                            Time = "16:00"
                        },
                        new
                        {
                            TimeSlotId = 75,
                            Booked = false,
                            Date = "2022-03-27",
                            Time = "17:00"
                        },
                        new
                        {
                            TimeSlotId = 76,
                            Booked = false,
                            Date = "2022-03-27",
                            Time = "18:00"
                        },
                        new
                        {
                            TimeSlotId = 77,
                            Booked = false,
                            Date = "2022-03-27",
                            Time = "19:00"
                        },
                        new
                        {
                            TimeSlotId = 78,
                            Booked = false,
                            Date = "2022-03-27",
                            Time = "20:00"
                        },
                        new
                        {
                            TimeSlotId = 79,
                            Booked = false,
                            Date = "2022-03-28",
                            Time = "08:00"
                        },
                        new
                        {
                            TimeSlotId = 80,
                            Booked = false,
                            Date = "2022-03-28",
                            Time = "09:00"
                        },
                        new
                        {
                            TimeSlotId = 81,
                            Booked = false,
                            Date = "2022-03-28",
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 82,
                            Booked = false,
                            Date = "2022-03-28",
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 83,
                            Booked = false,
                            Date = "2022-03-28",
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 84,
                            Booked = false,
                            Date = "2022-03-28",
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 85,
                            Booked = false,
                            Date = "2022-03-28",
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 86,
                            Booked = false,
                            Date = "2022-03-28",
                            Time = "15:00"
                        },
                        new
                        {
                            TimeSlotId = 87,
                            Booked = false,
                            Date = "2022-03-28",
                            Time = "16:00"
                        },
                        new
                        {
                            TimeSlotId = 88,
                            Booked = false,
                            Date = "2022-03-28",
                            Time = "17:00"
                        },
                        new
                        {
                            TimeSlotId = 89,
                            Booked = false,
                            Date = "2022-03-28",
                            Time = "18:00"
                        },
                        new
                        {
                            TimeSlotId = 90,
                            Booked = false,
                            Date = "2022-03-28",
                            Time = "19:00"
                        },
                        new
                        {
                            TimeSlotId = 91,
                            Booked = false,
                            Date = "2022-03-28",
                            Time = "20:00"
                        });
                });

            modelBuilder.Entity("Mission_12.Models.Appointment", b =>
                {
                    b.HasOne("Mission_12.Models.TimeSlot", "TimeSlot")
                        .WithMany()
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
